baking_softwaredev/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from users import views as user_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("register/", user_views.register, name="register"),
    path("profile/", user_views.profile, name="profile"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(template_name="users/password_reset.html"),
        name="password_reset",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path(
        "change-password/",
        auth_views.PasswordChangeView.as_view(
            template_name="users/password_change.html"
        ),
        name="password_change",
    ),
    path(
        "change-password/done",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html"
        ),
        name="password_change_done",
    ),
    path("", include("recipes.urls")),
]

handler404 = "recipes.error_views.page_not_found"
handler403 = "recipes.error_views.permission_denied"

recipes/urls.py
from django.urls import path

from . import views
from .views import RecipeDeleteView, CategoryCreateView

urlpatterns = [
    path("", views.recipe_overview, name="recipes-home"),
    path("advancedsearch/", views.advanced_search, name="advanced-search"),
    path("recipe/new", views.create_recipe, name="recipe-create"),
    path("recipe/<int:pk>", views.recipe_detail, name="recipe-detail"),
    path("recipe/<int:pk>/update", views.update_recipe, name="recipe-update"),
    path("recipe/<int:pk>/delete", RecipeDeleteView.as_view(), name="recipe-delete"),
    path("recipe/<int:pk>/addtocart", views.add_recipe_to_shopping_list, name="recipe-add-to-cart"),
    path("recipes/<str:username>", views.recipes_for_user, name="user-recipes"),
    path("categories", views.categories_overview, name="categories"),
    path(
        "categories/popup/new",
        CategoryCreateView.as_view(),
        name="category-create-popup",
    ),
    path("categories/new", views.create_category, name="category-create"),
    path(
        "categories/<int:pk>/selectrecipes", views.select_recipes, name="select-recipes"
    ),
    path("categories/<str:title>", views.category_recipe_view, name="category-recipes"),
    path("gallery", views.image_gallery, name="image-gallery"),
    # Shopping List
    path("shoppinglist", views.display_shopping_list, name="shopping-list"),
    path("shoppinglist/delete", views.delete_shopping_list, name="delete-shopping-list"),
    path("shoppinglist/<int:pk>/remove", views.remove_ingredients_from_shopping_list, name="remove-item-from-shopping-list"),
    # Ideas List
    path("ideas", views.display_ideas_list, name="ideas-list"),
    path("ideas/new", views.add_idea, name="add-idea"),
    path("ideas/<int:pk>/update", views.update_idea, name="update-idea"),
    path("ideas/<int:pk>/remove", views.delete_idea, name="delete-idea"),
]

recipes/models.py
import collections
from decimal import Decimal
from random import randint

from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.db import models
from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.urls import reverse
from model_utils.models import TimeStampedModel
from watson import search as watson

from .utils import get_image_size


class Category(models.Model):
    title = models.CharField(max_length=255, unique=True, verbose_name="Name")

    def __str__(self):
        return self.title

    def get_recipes(self, user):
        recipes = self.recipe_set.order_by("-modified")
        return filter_recipe_list(user, recipes)

    def get_absolute_url(self):
        return reverse("category-recipes", kwargs={"title": self.title})

    def random_recipe(self, user):
        """
        Returns a random recipe of the list of recipes that are accessible for this user.
        """
        return self.get_recipes(user).order_by("?").first()

    def get_primary_images(self, user):
        recipes = self.recipe_set.order_by("-modified")
        recipes = filter_recipe_list(user, recipes, filter_empty=False)
        return [rec.get_primary_image() for rec in recipes if rec.get_primary_image()]


class Food(models.Model):
    name = models.CharField(max_length=255, unique=True, verbose_name="Lebensmittel")

    def __str__(self):
        return self.name


class Recipe(TimeStampedModel):
    title = models.CharField(max_length=255, verbose_name="Titel")
    introduction = models.TextField(verbose_name="Einleitung", blank=True)
    servings = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        default=1,
        verbose_name="Portionen",
        blank=True,
        null=True,
    )
    directions = models.TextField(verbose_name="Zubereitung", blank=True)
    prep_time = models.CharField(
        max_length=100, verbose_name="Zubereitungszeit", blank=True
    )
    categories = models.ManyToManyField(Category, blank=True, verbose_name="Kategorien")
    author = models.ForeignKey(User, on_delete=models.SET_NULL, default=None, null=True)
    notes = models.TextField(verbose_name="Notizen", blank=True)
    secret_notes = models.TextField(verbose_name="Geheime Notizen", blank=True)
    related_recipes = models.ManyToManyField(
        "self",
        blank=True,
        symmetrical=False,
        verbose_name="zugehörige Rezepte",
    )
    public = models.BooleanField(default=False, verbose_name="für alle sichtbar")

    def __str__(self):
        return self.title

    def get_categories(self):
        return self.categories.all().order_by("title")

    def get_ingredients(self):
        return self.belongs_to.all()

    def get_absolute_url(self):
        return reverse("recipe-detail", kwargs={"pk": self.pk})

    def get_servings(self):
        return self.servings

    def get_images(self):
        return self.image_of.all().order_by("-is_primary")

    def get_primary_image(self):
        return self.image_of.filter(is_primary=True).first()

    def check_view_permissions(self, user):
        # admins may see everything
        if user.is_superuser:
            return

        # users that are not logged in may only see public recipes
        if not (user.is_authenticated or self.public):
            raise PermissionDenied

        # logged in users may only see their own and public recipes
        if not (self.author == user or self.public):
            raise PermissionDenied


class Ingredient(models.Model):
    amount = models.DecimalField(max_digits=6, decimal_places=3, verbose_name="Anzahl")
    unit = models.CharField(max_length=20, blank=True, verbose_name="Einheit")
    food = models.ForeignKey(Food, on_delete=models.PROTECT, verbose_name="Zutat")
    notes = models.TextField(blank=True, verbose_name="Notiz")
    recipe = models.ForeignKey(
        Recipe, related_name="belongs_to", on_delete=models.CASCADE, null=False
    )

    def __str__(self):
        return self.food.name

    def get_amount(self):
        return self.amount

    def get_unit(self):
        return self.unit

    def get_food_name(self):
        return self.food.name

    def get_notes(self):
        return self.notes


class RecipeImage(models.Model):
    image = models.ImageField(
        default="default.jpg", upload_to="recipe_pics", verbose_name="Bilder"
    )
    recipe = models.ForeignKey(
        Recipe, related_name="image_of", on_delete=models.CASCADE, null=True
    )
    is_primary = models.BooleanField(default=False, verbose_name="Titelbild")

    def __str__(self):
        return self.recipe.title

    def get_url(self):
        return self.image.url

    def get_height(self):
        height, _ = get_image_size(self.image)
        return height

    def get_width(self):
        _, width = get_image_size(self.image)
        return width


class ShoppingListRecipe(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.PROTECT, verbose_name="Rezept")
    servings = models.DecimalField(
        max_digits=6, decimal_places=3, verbose_name="Anzahl"
    )


class ShoppingList(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=None, null=True)
    recipes = models.ManyToManyField(
        ShoppingListRecipe, blank=True, verbose_name="ShoppingItems"
    )

    def __str__(self):
        return f"Einkaufsliste für {self.user.username}: {self.recipes.count()} Rezepte"

    def get_shopping_list_summary(self):
        # TODO: alle verlinkten Rezepte auch mit einrechnen
        # for now: verlinkte Rezepte sind nicht einberechnet

        # first: collect all ingredients
        ingredients = []
        for recipe in self.recipes.all():
            ingredients.extend(
                get_converted_ingredients(recipe.recipe, recipe.servings)
            )

        list_items = collections.defaultdict(int)

        for ingredient in ingredients:
            food = ingredient.food.name
            amount = ingredient.amount
            unit = ingredient.unit
            key = (food, unit)

            list_items[key] += amount

        list_items = [(f, u, a) for ((f, u), a) in list_items.items()]

        return sorted(list_items)


class Idea(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=255, verbose_name="Titel")
    notes = models.TextField(blank=True, verbose_name="Notiz")
    url = models.URLField(blank=True, verbose_name="Link")

    def __str__(self):
        f"{self.title} ({self.url}): {self.notes}"


def get_recipe_list(user):
    """
    Get the list of recipes accessible to the given user, ordered by least recently modified.

    If the given user is no registered and logged in user, only recipes marked as publicly available will be returned.
    If the given user is logged in, all recipes that are either publicly available or belong to the user will be returned.
    If the given user is a superuser, all recipes will be returned.
    """
    recipes = Recipe.objects.all().order_by("-modified")
    return filter_recipe_list(user, recipes)


def get_modifiable_recipe_list(user):
    return Recipe.objects.filter(author=user).order_by("title")


def get_search_results(
    user, search_term, categories, foods, excluded_foods, contains_all=False
):
    """
    Filter list of recipes according to the search. Only the recipes accessible to the given users will be searched.
    Returns a list of recipes ordered by title.

    search_term: String. Recipe.title, Recipe.instructions, Recipe.notes will be searched for this term
    categories: List of Category Objects. Only recipes of these categories will be returned. If empty all categories are searched.
    foods: List of Food Objects. Only recipes containing these foods as ingredients will be returned. If empty all foods are considered.
    excluded_foods: List of Food Objects. Only recipes NOT containing these foods as ingredients will be returned.
    contains_all: If True, only recipes containing all Food Objects given in 'food' as ingredient will be returned.
                  If False, recipes containing any of the foods will be returned.
    """
    # get the list of recipes accessible to the given user
    recipes = get_recipe_list(user)

    # if a search term is given: use watson to search the recipe titles, instructions and notes for the given term
    if search_term:
        results = watson.search(search_term)
        pks = [r.object_id_int for r in results]
        recipes = recipes.filter(pk__in=pks)

    # if category objects are given: keep only recipes of these categories
    if categories:
        recipes = recipes.filter(categories__in=categories)

    # if food objects are given: filter recipes according to contains_all
    if foods:
        # if contains_all is set to True: keep only recipes containing all given foods
        if contains_all:
            for food in foods:
                ingredients = Ingredient.objects.filter(food=food)
                recipe_pks = ingredients.values_list("recipe", flat=True)
                recipes = recipes.filter(pk__in=recipe_pks)
        # if contains_all is set to False: keep only recipes containing any of the given foods
        else:
            ingredients = Ingredient.objects.filter(food__in=foods)
            recipe_pks = ingredients.values_list("recipe", flat=True)
            recipes = recipes.filter(pk__in=recipe_pks)

    # if exclude food objects are given: keep only recipes containing none of the given foods
    if excluded_foods:
        ingredients = Ingredient.objects.filter(food__in=excluded_foods)
        recipe_pks = ingredients.values_list("recipe", flat=True)
        recipes = recipes.exclude(pk__in=recipe_pks)
        recipes = recipes.exclude(related_recipes__pk__in=recipe_pks)

    return recipes.order_by("title")

recipes/templates/recipes/advanced_search.html
{% extends 'recipes/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<h3>Suche</h3>
<form>
    <div class="form-group">
        <input class="form-control" id="searchbox_advanced" name="q" type="text" value="{{request.GET.q}}" placeholder="Suche"
            aria-label="Suche">
    </div>
    <div class="form-row">
        <div class="col">
            <div class="my-4">
                {{ category_form|crispy }}
            </div>
        </div>
        <div class="col">
            <div class="my-4">
                {{ food_form|crispy }}
            </div>
        </div>
    </div>
    <div class="form-row">
        <div class="col-md-6">
            <div class="my-4">
                {{ exclude_food_form|crispy }}
            </div>
        </div>
    </div>

    <button class="btn btn-secondary my-2 my-sm-0" type="submit"><i class="fas fa-search"></i> Suchen</button>
</form>
<hr>
<!-- 
    search results here
 -->
{% if search_term %}
<h3>Suchergebnisse ({{ num_results }})</h3>
{% endif %}
{% if search_results %}
<div class="card-columns">
    {% for recipe in search_results %}
    {% include "recipes/recipe_card.html" with recipe=recipe %}
    {% endfor %}
</div>
{% else %}
Keine Rezepte gefunden.
{% endif %}
{% endblock content %}


{% block javascript %}
    <script src="{% static 'recipes/js/selectpicker.js' %}"></script>
{% endblock javascript %}

recipes/templates/recipes/base.html
{% load static %}
{% load fontawesome_5 %}
{% load crispy_forms_tags %}
<!doctype html>
<html lang="de">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- google fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Shadows+Into+Light&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    {% fontawesome_5_static %}
    <link rel="stylesheet" type="text/css" href="{% static 'recipes/main.css' %}" />
    <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/css/bootstrap-select.min.css">
    <link rel="icon" 
      type="image/png" 
    <link rel="shortcut icon" type="image/png" href="{% static 'recipes/favicon.ico' %}"/>  
    <!-- PhotoSwipe JS Library -->
    <!-- Core CSS file -->
    <link rel="stylesheet" href="{% static "recipes/photoswipe.css" %}">

    <!-- Skin CSS file (styling of UI - buttons, caption, etc.)
     In the folder of skin CSS file there are also:
     - .png and .svg icons sprite, 
     - preloader.gif (for browsers that do not support CSS animations) -->
    <link rel="stylesheet" href="{% static "recipes/default-skin.css" %}">

    <!-- PhotoSwipe JS Library -->
    <!-- Core JS file -->
    <script src="{% static "recipes/js/photoswipe.min.js" %}"></script>
    <!-- UI JS file -->
    <script src="{% static "recipes/js/photoswipe-ui-default.min.js" %}"></script>
    <title>Recipes</title>
</head>

<body>
    {% include 'recipes/navbar.html' %}
    <main role="main" class="container my-4">
        {% if messages %}
        {% for message in messages %}
        <div class="alert {{ message.tags|default:"alert-danger" }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}

        {% block content %}
        {% endblock content %}
    </main>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/js/bootstrap-select.min.js"></script>

    {% block javascript %}
    {% endblock javascript %}
</body>

</html>

recipes/templates/recipes/categories.html
{% extends "recipes/base.html" %}
{% block content %}
<div class="row my-4 mx-2">
  <h3 class="overview-title">Kategorien</h3>
  <div class="ml-auto">
    <a class="btn btn-outline-secondary" href="{% url 'category-create' %}">Kategorie<i class="col-2 fas fa-plus"></i></a>
  </div>
</div>
<div class="card-columns">
  {% for cat, recipes in categories %}
  <div class="card">
    <div class="card-header">
      <h5 class="card-title text-center"><a class="recipe-card-link"
          href="{% url 'category-recipes' cat.title %}">{{ cat.title }}</a></h5>
    </div>
    <div class="card-body">
      {% if recipes %}
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Rezepte in dieser Kategorie</li>
        {% if recipes|length > 2 %}
        <li class="list-group-item"><a class="recipe-card-link-small"
            href="{% url 'recipe-detail' recipes.0.pk %}">{{ recipes.0.title }}</a></li>
        <li class="list-group-item"><a class="recipe-card-link-small"
            href="{% url 'recipe-detail' recipes.1.pk %}">{{ recipes.1.title }}</a></li>
        <li class="list-group-item"><a class="recipe-card-link-small"
            href="{% url 'category-recipes' cat.title %}">...mehr...</a></li>
        {% else %}
        {% for rec in recipes %}
        <li class="list-group-item"><a class="recipe-card-link-small"
            href="{% url 'recipe-detail' rec.pk %}">{{ rec.title }}</a></li>
        {% endfor %}
        {% endif %}
      </ul>
      {% else %}
      <p class="card-text text-center">Bisher keine Rezepte in dieser Kategorie.</p>
      {% endif %}
    </div>
  </div>
  {% endfor %}
</div>

{% if is_paginated %}
{% include "recipes/pagination.html" %}
{% endif %}
{% endblock content %}

recipes/templates/recipes/category_form.html
{% extends "recipes/base.html" %} {% load crispy_forms_tags %} {% block content %}
<div class="content-section">
  <form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Neue Kategorie</legend>
      {{ form|crispy }}
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-secondary" type="submit">Speichern</button>
    </div>
  </form>
</div>
{% endblock content %}

recipes/templates/recipes/idea_form.html
{% extends "recipes/base.html" %} {% load crispy_forms_tags %} {% block content %}
<div class="content-section">
  <form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Neue Idee</legend>
      {{ form | crispy }}
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-secondary" type="submit">Speichern</button>
    </div>
  </form>
</div>
{% endblock content %}

recipes/templates/recipes/ideas_list.html
{% extends 'recipes/base.html' %}
{% block content %}
    <div class="row my-4 mx-2">
        <h1 class="overview-title">Ideenliste</h1>
        <div class="ml-auto">
            <a class="btn btn-outline-secondary" href="{% url 'add-idea' %}">Idee<i class="col-2 fas fa-plus"></i></a>
        </div>
    </div>

    <div class="table-responsive">
    <table class="table">
        <tr>
            <th>Titel</th>
            <th>Notizen</th>
            <th></th>
        </tr>
        {% for idea in ideas %}
        <tr>
            <td><a href={{ idea.url }} target="_blank">{{ idea.title }}</a></td>
            <td>{{ idea.notes }}</td>
            <td>
                <a href="{% url 'update-idea' pk=idea.pk %}" class="btn text-dark"><i class="fas fa-edit fa-sm"></i></a>
                <a href="{% url 'delete-idea' pk=idea.pk %}" class="btn text-danger"><i class="fas fa-trash fa-sm"></i></a>
            </td>
        </tr>
        {% endfor %}
    </table>
</div>

{% endblock content %}

recipes/templates/recipes/image_slideshow.html
{% load static %}
<div id="recipeImageIndicators" class="carousel slide" data-interval="false">
    <ol class="carousel-indicators">
        {% for img in images %}
        <li data-target="#recipeImageIndicators" data-slide-to="{{forloop.counter0}}" class="active"></li>
        {% endfor %}
    </ol>
    <div class="carousel-inner">
    {% if images %}
        {% for img in images %}
        <div class="carousel-item {% if forloop.first %} active {% endif %}">
            <img class=" d-block w-100" src="{{img.get_url}}" alt="Recipe Image">
        </div>
        {% endfor %}
    {% else %}
        <div class="carousel-item active">
            <img class=" d-block w-100" src="{% static 'recipes/default.jpg' %}" alt="Default Image">
        </div>
    {% endif %}
    </div>
    <a class="carousel-control-prev" href="#recipeImageIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#recipeImageIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

recipes/templates/recipes/navbar_search.html
<form class="form-inline my-2 mx-2 my-lg-0" id="searchform" accept-charset="utf-8" action={% url 'advanced-search' %}
    method=GET>
    <div class="input-group">
        <input id="searchbox" name="q" type="text" class="form-control" value="{{request.GET.q}}" placeholder="Suche" aria-label="Suche">
        <div class="input-group-append">
            <a class="btn btn-outline-secondary nav-link-button" href="{% url 'advanced-search' %}"><i class="fas fa-sliders-h"></i></a>
            <button class="btn btn-outline-secondary nav-link-button" type="submit"><i class="fas fa-search"></i></button>
        </div>
    </div>
</form>

recipes/templates/recipes/recipe_form.html
{% extends "recipes/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<script src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
<div class="content-section">
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% if ingredients.non_form_errors or images.non_form_errors %}
    <div class="alert alert-danger" role="alert">
      {{ ingredients.non_form_errors }}
      {{ images.non_form_errors }}
    </div>
    {% endif %}
    <fieldset class="form-group">
      {% if form.instance.pk %}
      <legend class="border-bottom mb-4">Rezept ändern</legend>
      {% else %}
      <legend class="border-bottom mb-4">Neues Rezept</legend>
      {% endif %}
      <div class="form-group mb-0">
        {{ form.title|as_crispy_field }}
      </div>
      <div class="form-group mb-0">
        {{ form.public|as_crispy_field }}
      </div>
      <div class="form-group mb-0">
        {{ form.introduction|as_crispy_field }}
      </div>
      <div class="prep-time form-group mb-0">
        {{ form.prep_time|as_crispy_field }}
      </div>
      <div class="servings-create-view form-group mb-0">
        {{ form.servings|as_crispy_field }}
      </div>

      <div>
        <h5 class="mt-5">Zutaten</h5>
        <table class="table table-striped">
          {{ ingredients.management_form|crispy }}

          {% for form in ingredients.forms %}
          <tr class="ingredients-{{ ingredients.prefix }}">
            {% for field in form.visible_fields %}
            <td>
              {# Include the hidden fields in the form #}
              {% if forloop.first %}
              {% for hidden in form.hidden_fields %}
              {{ hidden }}
              {% endfor %}
              {% endif %}
              {{ field.errors.as_ul }}
              {{ field|as_crispy_field }}
            </td>
            {% endfor %}
          </tr>
          {% endfor %}

        </table>
      </div>
      <script src="{% static 'recipes/js/jquery.formset.js' %}"></script>
      <script type="text/javascript">
        $('.ingredients-{{ ingredients.prefix }}').formset({
          addText: 'Zutat <i class="col-2 fas fa-plus"></i>',
          deleteText: '<i class="col-2 fas fa-trash"></i>',
          prefix: '{{ ingredients.prefix }}',
          addCssClass: 'btn btn-secondary',
          deleteCssClass: 'btn text-danger'
        });
      </script>

      <div class="form-group mb-0">
        {{ form.directions|as_crispy_field }}
      </div>
      <div class="form-group mb-0">
        {{ form.notes|as_crispy_field }}
      </div>
      <div class="form-group mb-0">
        {{ form.secret_notes|as_crispy_field }}
      </div>
      <div class="row">
        <div class="col md-6">
          <div class="form-group mb-0">
            {{ form.related_recipes|as_crispy_field }}
          </div>
        </div>
        <div class="col md-6">
          <div class="form-group mb-0">
            {{ form.categories|as_crispy_field }} {{form.media}}
          </div>
        </div>
      </div>


      <div>
        <h5 class="mt-5">Bilder</h5>
        <table class="table table-striped">
          {{ images.management_form|crispy }}

          {% for form in images.forms %}
          <tr class="images-{{ images.prefix }}">
            {% for field in form.visible_fields %}
            <td>
              {# Include the hidden fields in the form #}
              {% if forloop.first %}
              {% for hidden in form.hidden_fields %}
              {{ hidden }}
              {% endfor %}
              {% endif %}
              {{ field.errors.as_ul }}
              {{ field|as_crispy_field }}
            </td>
            {% endfor %}
          </tr>
          {% endfor %}
        </table>
      </div>
      <script type="text/javascript">
        $('.images-{{ images.prefix }}').formset({
          addText: 'Bild <i class="col-2 fas fa-plus"></i>',
          deleteText: '<i class="col-2 fas fa-trash"></i>',
          prefix: '{{ images.prefix }}',
          addCssClass: 'btn btn-secondary',
          deleteCssClass: 'btn text-danger'
        });
      </script>

      <div class="form-group">
        <button class="btn btn-outline-secondary" type="submit">Speichern</button>
      </div>


    </fieldset>
  </form>
</div>
{% endblock content %}

{% block javascript %}
<script src="{% static 'recipes/js/selectpicker.js' %}"></script>
<script type="text/javascript">
  // Hack to re-render the category selector if a new category was added
  // listening to on('change') does not work
  let oldLen = 0
  setInterval(() => {
    const newLen = $('#id_categories option').length
    if (newLen != oldLen) {
      oldLen = newLen
      $('#id_categories').selectpicker('refresh')
    }
  }, 500)
</script>
{% endblock javascript %}